zuul.d/pipelines.yaml

Based on Monty Taylor (mordred) Zuul configuration.
Avoid sf-bot *and* ansibullbot both informing about merge conflicts.

Add third-party-check to avoid merge conflict warnings

---

playbooks/base-minimal-test/post.yaml
playbooks/base-minimal-test/pre.yaml
playbooks/base-minimal/post.yaml
playbooks/base-minimal/pre.yaml
zuul.d/jobs.yaml

These jobs are not used at the moment, but will be once we re-parent base to them.  The goal here is to move base into ansible-zuul-jobs allow for users to propose speculative changes to them.

Create base-minimal / base-minimal-test jobs

---

zuul.d/secrets.yaml

It seems like config-update job is failing because two secrets
define different key format for the same host.
This change should fix config-update POST_FAILURE errors.

secret: fix known host to use the same key

---

zuul.d/secrets.yaml

The keys that were provided were encrypted with a \n in the file (vim
default) This lead to the access key being "access_key\n" which is not a
valid access_key.
Newly generated content have been generated with a vim file configured
to not have a \n (:set noeol, :set binary) the content of the access key
should be correct now.

Secrets: Provide encrypted keys w/o \n

---

resources/ansible.yaml

We should keep zuul-config branches, since it is a config-project, it
would be possible to merge code into another branch, and break zuul.

Exclude unprotected branches for ansible/zuul-config

---

zuul.d/projects.yaml

We no longer want to run jobs on ansible/ansible-runner, as we are in
the process of moving the repo into zuul.ansible.com.

Remove ansible/ansible-runner jobs

---

resources/ansible.yaml

We have migrated this repo to zuul.ansible.com.

Remove ansible/ansible-runner from zuul tenant configuration

---

playbooks/run_awx_tests.yml
roles/run_awx_tests/tasks/main.yml
roles/run_awx_tests/templates/cloudbuild.yml.j2
roles/run_awx_tests/templates/pod.yml.j2
zuul.d/awx-jobs.yaml

I might need to iterate on this a couple times but since we dont have pre-merge testing on this repo ¯\_(ツ)_/¯
I’ve tested this in zuul-jobs and it works. Moving here inside of the config-project so it cant be attacked.

Add playbook and role for running awx tests in k8s

---

resources/ansible.yaml

This change should prevent MERGER_FAILURE caused by awx feature branch workflow
that may results in:
ValueError: Could not parse git-remote prune result:
' refs/remotes/origin/HEAD will become dangling!'

AWX: skip unprotected branch

---

roles/run_awx_tests/tasks/main.yml

The schema differ job isn't working in AWX (and also not new job I'm trying to add). It runs:
```
kubectl exec awx-detect-schema-change-4701 -- bash -c '/entrypoint.sh '/start_tests.sh detect-schema-change''
```
This is trying to make this work correctly. The end result here is that `start_tests.sh` does not get any arguments, so it runs tests and doesn't detect schema change.

Use double quotes to avoid quote conflict

---

playbooks/base-minimal/post.yaml
roles/log-classify/defaults/main.yaml
roles/log-classify/tasks/run.yaml

This change updates the base job with latest changes:
- Use the new log-classify role
- Remove the deprecated emit-job-report
- Add the zuul_log_compress flag

log-classify: update role with latest change

---

zuul.d/pipelines.yaml

Clean-check means that gate does not start without a successful check.
Turns out that is a requirement that has been lifted from the openstack old days, and it we could remove it.
Accepting this change results in:
once you approve and add the gate-it tag, then check jobs are canceled and the change goes directly to gate.

gate: remove clean-check requirement

---

resources/ansible.yaml

This would prevent issue when unexpected dev branch are pushed
to the ansible/zuul-jobs project.
Before merging that change we need to make sure the master branch
of ansible/zuul-jobs is actually protected.

ansible/zuul-jobs: disable unprocted branches for the zuul-jobs project

---

roles/run_awx_tests/tasks/main.yml

* kubectl cp invoked with | was causing a newline to get added, causing
an error. This seems to be a behavior change in ansible-2.8 (didn't
happen in 2.7)
* This change explicitly specifies the destination in hopes to avoid the
error that is happening. Note that a newline will still be added

pushing awx schema was erroring on artifact copy

---

roles/run_awx_tests/tasks/main.yml

* Was using the full path of the remote file when downloading locally.
i.e. "/foo/bar/file.txt" copied to "/meyers/" would result in
"/meyers/foo/bar/file.txt". Instead "/foo/bar/file.txt" copied to
"/meyers/" would result in "/meyers/file.txt"

strip remote file dir info when copying local

---

zuul.d/jobs.yaml

This change replaces the legacy runc node to the new
pod node to prevent NODE_FAILURE error.

base: switch base nodeset to pod

---

playbooks/base-openshift/post.yaml
playbooks/base-openshift/pre.yaml
zuul.d/jobs.yaml

This change enables using pod-fedora node to run simple job like
the linters.

jobs: add a base-openshift job to work for linter using pod-fedora

---

playbooks/linters.yaml
zuul.d/jobs.yaml

This change adds a new config-linters job that would use the
new base job that works with kubectl node.

Add config-linters job

---

zuul.d/projects.yaml

- We've removed the old ui code from devel. 
- There will now only be one zuul job for ui - `awx-ui`. 
- The `make` targets it uses are now running the tests for the new ui, so we can delete the `*-next` config

Remove old test config

---

playbooks/base-openshift/post.yaml

This change fixes this issue:
The error was: 'site_sflogs' is undefined

base-openshift: fix typo in logs secret

---

zuul.d/jobs.yaml

This change updates the default nodeset to f32.

zuul-jobs: fix linters job name

---

zuul.d/jobs.yaml

This is no longer necessary and this can be defined in the zuul-jobs project
directly.
Depends-On: https://github.com/ansible/zuul-jobs/pull/45

zuul-jobs: remove the project definition

---

playbooks/base-minimal/post.yaml

This change fixes an issue where it is no longer possible to use
a secret attribute for hosts.

Update base post playbook hosts definition

---

zuul.d/jobs.yaml

This reverts commit dbf05371a4383b99fa53d2667ad65d45d114241c.

Revert "openshift: bump the base label to pod-fedora-33"

---

resources/ansible.yaml

ansible-zuul-jobs should actually be an untrusted configuration
project.

ansible-zuul-jobs is actually an untrusted project

---

resources/ansible.yaml

It's not clear why the job from the main branch are not imported. This
explicitly turns exclude-unprotected-branches off.

ansible-zuul-jobs: exclude-unprotected-branches: false

---

resources/ansible.yaml

We will use this directory to store the nodeset for SoftwareFactory. This
way we can maintain to different nodeset files in the same repository.

ansible-zuul-jobs: extra-config-paths zuul.sf.d/nodesets.yaml

---

resources/ansible.yaml

Now we've got the zuul.{ansible,sf}.d/ directores in place, we can use
the same configuration for the two platforms.

switch on ansible/ansible-zuul-jobs

---

resources/ansible.yaml

resources: add a.netcommon and a.utils

---

zuul.d/jobs.yaml

build-ansible-collection was defined two times and this was
resulting in the pre-run been called two times in a row.

define build-ansible-collection only one time

---

playbooks/publish/ansible-automation-hub.yaml
playbooks/publish/ansible-galaxy.yaml

With SoftwareFactory, there is no ansible-galaxy on the Zuul Executor:
/bin/sh: /opt/venv/zuul-ansible/2.9.16/bin/ansible-galaxy: No such file or directory

run the publish jobs on the controller

---

roles/use-our-mirror/tasks/main.yaml

Ansible 2.9's uri module ignores the `validate_certs` parameter. This
time we call `curl` directly.
Also, fix two syntax errors.

use-our-mirror: replace uri by a curl call

---

roles/upload-ansible-collection-fork/defaults/main.yaml

We run the role on the controller, the artifacts are in the ~/artifacts
directory.

upload-ansible-collection-fork: adjust the artifacts path

---

roles/use-our-mirror/tasks/main.yaml

We can safely abort after 3s. There is no point waiting more.

use-our-mirror: reduce curl's timeout

---

zuul.d/jobs.yaml

This reverts commit 708a31d2b8dd64c21e350e787141405c526f5020.
```
The conditional check 'zuul_success | bool' failed. The error was: error while evaluating conditional (zuul_success | bool): 'zuul_success' is undefined
The error appears to be in '/var/lib/zuul/builds/f1a7636966e34e08b6d5ac92288865dc/trusted/project_0/github.com/ansible/zuul-config/playbooks/publish/ansible-galaxy.yaml': line 6, column 11, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
block:
- name: Run upload-ansible-collection-fork
^ here
```

Revert "publish jobs: don't use post-run"

---

zuul.d/projects.yaml

Sounds like this was not enough.
See: https://github.com/ansible/ansible-zuul-jobs/pull/1303#issuecomment-1014717991

adjust the default-branch regex to include github.com/ prefix

---

zuul.d/projects.yaml

The matching by regex does not work as expected. community.vmware still
uses `master` as default branch.
See: https://github.com/ansible/ansible-zuul-jobs/pull/1303#issuecomment-1014740313

projects: set a default branch per project

---

zuul.d/projects.yaml

Created this PR in a similar vein to this PR: https://github.com/ansible/zuul-config/pull/207
To try and fix this error in the CI:
https://github.com/ansible-collections/community.aws/pull/875#issuecomment-1016160880
```
build-ansible-collection : ERROR Project github.com/ansible-collections/ansible.utils does not have the default branch master in 16s
```

Add project config to fix CI error

---

zuul.d/projects.yaml

By removing this, we triggered this error:
```
ERROR Project github.com/ansible-collections/ansible.netcommon does not have the default branch master in 19s
```
See: https://github.com/ansible-collections/community.aws/pull/875

default-branch: put back the rules for the ansible-collections

---

zuul.d/projects.yaml

We should not need these jobs when https://github.com/ansible/ansible-zuul-jobs/pull/1304
will be ready.

eos: remove the network-ee-container-image-jobs template

---

playbooks/base/pre.yaml

The containers already come with git and we don't need tox.

container: don't install git/tox

---

zuul.d/jobs-ee.yaml

We should not need these jobs once
https://github.com/ansible/ansible-zuul-jobs/pull/1304 is merged.

disable the buildset related jobs

---

playbooks/base/pre.yaml

e.g:
```
2022-01-21 17:13:22.009102 | TASK [Install git and tox]
2022-01-21 17:13:28.680739 | fedora-35 | ERROR
2022-01-21 17:13:28.681005 | fedora-35 | {
2022-01-21 17:13:28.681061 | fedora-35 |   "msg": "Failed to download metadata for repo 'updates': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried",
2022-01-21 17:13:28.681103 | fedora-35 |   "rc": 1,
2022-01-21 17:13:28.681141 | fedora-35 |   "results": []
2022-01-21 17:13:28.681178 | fedora-35 | }
```

disable the mirror until the problem with updates is resolved

---

playbooks/base/pre.yaml

Mirrors have been redeployed and are in a sane state.
This reverts commit c88fc6ea4c508bf08c852acc831bb32b325cef6d.

Revert "disable the mirror until the problem with updates is resolved"

---

zuul.d/projects.yaml

The use the ansible-ee-tests template to run the EE jobs.

arista-eos: use the ansible-ee-tests template

---

zuul.d/projects.yaml

ansible-collections-arista-eos depends on network-ee-build-container-image
which we don't run.

eos: disable ansible-collections-arista-eos

---

playbooks/set-up-mirrors/main.yaml

Fail if we've got just 5GB of disk remaining

set-up-mirrors: fail if disk is full

---

playbooks/build-ansible-collection-pod/run.yaml

`ansible_user_dir` targets /root which does not exist in the container.

build-ansible-collection-pod: avoid ansible_user_dir

---

playbooks/base/pre.yaml
playbooks/build-ansible-collection-pod/run.yaml

This to avoid error like this one:
```
ERROR: Invalid requirement: '//src/github.com/ansible-network/releases'
```

build-ansible-collection-pod: avoid double /

---

playbooks/build-ansible-collection-pod/run.yaml

The zuul-output/artifacts files are automatically pulled by
fetch-output-openshift.

build-ansible-collection-pod: use zuul-output directory

---

playbooks/build-ansible-collection-pod/post.yaml

The artifacts are now generated in "{{ ansible_user_dir }}/zuul-output/artifacts"

build-ansible-collection-pod: looks for artifacts at the right place

---

resources/ansible.yaml

The ara job and pipeline configuration is inside their own repositories
so we need to not exclude it.

Allow zuul configuration to be loaded from ara repos

---

zuul.d/pipelines.yaml

The patterns are they are now are causing issues like pre-release and
release triggering on the same tag or not triggering at all.
We had particular patterns in place in the previous zuul configuration,
let's continue using them unless there is an issue.
See the following for details:
- https://github.com/ansible/project-config/commit/9b842f9e8b299ea03cdc1431f800b561ec44e9b1
- https://github.com/ansible/project-config/commit/6f49b47f229f63b9357348c5f81e7ad7de7a67e3

Update (pre-)release pipeline patterns to previous ones

---

zuul.d/pipelines.yaml

These comments have been flooding community.general and other community collections since the softwarefactory-project.io Zuul has been added to them ([example](https://github.com/ansible-collections/community.docker/pull/293#issuecomment-1030696483)).

Stop annoying comments on successful third-party-check runs

---

playbooks/publish/pypi.yaml

virtualenv command is deprecated.

release-ansible-python: use -m venv to create venv

---

zuul.d/projects.yaml

This is not supposed to work because of the lack of tox.ini file.
It's just to validate the project configuration. The change will
be revert later.

plugin_builder: apply ansible-python-jobs

---

zuul.d/jobs.yaml

This job is the parent of the workshops-tox-integration-* jobs
defined in ansible-zuul-jobs.

define ansible-workshops-tox-integration job

---

playbooks/set-up-mirrors/main.yaml

We don't use Avahi anymore to expose the node.

set-up-mirrors: do not use Avahi

---

playbooks/set-up-mirrors/main.yaml

We've got some IPv6 connectivity problems with at least one of our
region.

set-up-mirrors: disable IPv6 for now

---

zuul.d/jobs.yaml

We cannot reuse yet the nodeset name defined in ansible-zuul-jobs.
This because we load a part of the configuration from
zuul.sf.d/nodesets.yaml too and this confuse Zuul.

ansible-workshops-tox-integration: flatten the nodeset

---

zuul.d/projects.yaml

We don't need these templates anymore:
- ansible-python-jobs
- ansible-ee-tests

ansible.plugin_builder: remove some templates

---

resources/ansible.yaml

They will be defined directly in ansible-zuul-jobs when
https://github.com/ansible/ansible-zuul-jobs/pull/1398 is merged.

network-ee: do not load local jobs

---

zuul.d/jobs.yaml

ansible-cloud-centos-8-stream has been replaced by ansible-cloud-centos-8-stream-tiny.

ansible/workshop: update the node label

---

zuul.d/jobs.yaml

We still have a problem with k1s.
This reverts commit ea754b49ec2d73e4a52e324e080806dc313700dc.

Revert "Revert "use regular VM until the k1s problem is fixed""

---

zuul.d/jobs.yaml

We hit `retry_limit` rather often, the problem may be resolved soon by the
platform upgrade.

increase the number of retry to 6

---

scripts/upload-vmware-image.sh

We don't use the region anymore because it depends on Ceph
(boot-from-volume=True).

upload-vmware-image.sh: don't upload images on sjc1

---

scripts/upload-vmware-image.sh

We don't need to upload raw image anymore because we don't use
Ceph volume anymore.

upload-vmware-image.sh: upload qcow2 image

---

playbooks/base/pre.yaml

python3-tox is not in EPEL. We may want to reconsider this in the future.
For now, this is good enough.

enable EPEL on RHEL

---

playbooks/downstream-ee-integration/pre.yaml
zuul.d/jobs.yaml

- rename the playbook
- use static quote to protect the password, the previous solution with the
`quote` filter seems to be broken.

downstream-ee: rename the playbook

---

roles/release-ansible-collection/tasks/main.yml

/tmp is a RAM FS, we can exhauste the free space if we use it to store
large amount of data.

release-ansible-collection: point TMPDIR on a FS tmp dir

---

zuul.d/projects.yaml

We're not really able to maintain these jobs and continue running the ansible-test
based jobs.

disable the Upstream-EE jobs

---

zuul.d/projects.yaml

We are moving away from using Zuul for releasing to PyPI.

Disable PyPI releases for builder/runner

---

zuul.d/projects.yaml

Signed-off-by: Rohit Thakur <rohitthakur2590@outlook.com>

update Ansible yang push-to-ah job

---

zuul.d/pipelines.yaml

Fixes the bug introduced in https://github.com/ansible/project-config/pull/782. Making the `-` optional allowed the later part of the regex to match the second digit of a two-digit patch release number. This change allows a pre-release indicator without `-` only when it doesn't start with a digit.

Stop matching valid non-pre releases such as 1.0.10 as pre-releases

---

zuul.d/projects.yaml

As requested on Matrix by resmo.

enable publish-to-galaxy-3pci for hetzner.hcloud

---

resources/ansible.yaml
zuul.d/projects.yaml

Since community.azure 2.0.0 the collection is a dead shell that will no longer be released or built.
CC @Andersson007

Remove community.azure

---

resources/ansible.yaml

As README looks a bit outdated I created the [issue](https://github.com/ansible/zuul-config/issues/425) to avoid questions like the following in future:
Is it enough what i did here to enable publishing on Galaxy by Zuul or I need to do something else?
Thanks

community.nextcloud: Add publishing on Galaxy by Zuul

---

resources/ansible.yaml

community.arduino: Add publishing on Galaxy by Zuul
relates to https://github.com/ansible/community/issues/587 and https://github.com/ansible-community/community-team/issues/37

community.arduino: Add publishing on Galaxy by Zuul

---

zuul.d/projects.yaml

remove the github.com/ansible/workshops from zuul.  We are going to use Ansible/Github Actions to provide testing instead of zuul

Update projects.yaml to remove ansible/workshops

---

zuul.d/projects.yaml

We are about to promote `cloudtrail` and `cloudtrail_info`. We need
to merge the full branch and preserve the history.

amazon.aws: temporarily use the merge strategy

---

zuul.d/projects.yaml

https://github.com/ansible-collections/amazon.aws/pull/997 is now merged.
This reverts commit 4ab3356b9ada86aa4b62b61ee40f68a3d70d249a.

Revert "amazon.aws: temporarily use the merge strategy"

---

zuul.d/projects.yaml

I think this should do the job while we figure out how to make the release elsewhere.

Restore the release jobs for ansible.utils

---

resources/ansible.yaml

The migration is done, no need to source this directory.

ansible/ansible-zuul-jobs: ignore zuul.sf.d/ directory

---

playbooks/build-ansible-collection/run.yaml

I'm trying to understand why the artifacts of the periodical jobs are missing.

expose the artifacts in the logs directory

---

zuul.d/pipelines.yaml

The option merge-failure was removed from zuul. Use the new merge-conflict keyword to fix:
extra keys not allowed @ data['merge-failure']

Remove deprecated option from pipelines.yaml

---

zuul.d/projects.yaml

amazon.cloud sanity and unit jobs are moved to GitHub Action

Remove amazon.cloud job

---

zuul.d/projects.yaml

The testing has been migrated to GHA from zuul.

Remove cloud.aws_ops template

---

zuul.d/projects.yaml

The jobs are moved to GHA. So removing the project from zuul.

Remove aws_troubleshooting project

---

zuul.d/projects.yaml

Summary:
Moved ansible-collections/kubernetes.core unit test to GHA. So removing the corresponding template from zuul-config.

Remove ansible-collections-kubernetes-core-units

---

resources/ansible.yaml
zuul.d/projects.yaml

Before being merged, required secrets to push to automation-hub and galaxy-hub should be created on kubernetes.core repository first

Remove reference to kubernetes.core collection

---

resources/ansible.yaml

Without Github App installation, Zuul hits rate limit, which may got stuck and restart takes ages, because it is waiting for Github API quota reset.

Switch Zuul connection because of missing GH app configuration

---

zuul.d/projects.yaml

This job has been migrated into GHA, therefore we do need Zuul to run it anymore.
ansible-python-jobs consists in `ansible-tox-linters` job only, more details here https://github.com/ansible/ansible-zuul-jobs/blob/94cae8b1a66775e122df3bd68ca45be757ba1ff7/zuul.d/project-templates.yaml#L17-L26

Remove ansible-tox-linters for cloud.common

---

resources/ansible.yaml

Corrects oversight when the other Ansible Collections for SAP (sap_install, sap_operations, sap_libs) were added to zuul-config

Add missing SAP collection

---

playbooks/validate-ansible-galaxy-token/run.yaml
zuul.d/jobs.yaml
zuul.d/secrets.yaml

The API we were using to validate tokens no longer exists and no suitable replacement is immediately obvious.  Disable this check for now.
Collection uploads are still failing, despite the token working from the cli, so re-encrypt the Galaxy token and refresh.
Because we can't run the token validate job however, we don't have any real way to test this without someone actually doing a collection release.

Re-encrypt galaxy token and disable validity check

---

playbooks/validate-ansible-galaxy-token/run.yaml

This re-enables the galaxy token check with a new url that works for galaxy ng.

Re-enable galaxy token validation

---

zuul.d/projects.yaml

Remove ansible-collections-cloud-common, as the jobs have been migrated to GHA.

Remove ansible-collections-cloud-common

---

zuul.d/projects.yaml

Depends-On: #545 
Refer: https://issues.redhat.com/browse/ACA-1295
This PR adds the `publish-to-automation-hub` job to the validated content cloud repos.

Add publish-to-automation-hub for validated content cloud repos

---

README.rst
zuul.d/projects.yaml

Make sure that only the `publish-to-galaxy-plain` template (https://github.com/felixfontein/ansible-zuul-jobs/commit/0495329eda10728e0928c990992ab21021a27f70) is used for the set of collections, instead of Zuul merging both the `publish-to-galaxy-plain` and `publish-to-galaxy-3pci` templates for them.

Use publish-to-galaxy-plain for collections in ansible-collections/community.*, with explicit list of exceptions

---

playbooks/redhat-openshift/pre.yaml
playbooks/redhat-openshift/run.yaml
roles/upload-ansible-collection-fork/tasks/main.yaml
zuul.d/jobs.yaml
zuul.d/projects.yaml

`redhat.openshift` downstream collection needs to be published from `community.okd` repository therefore we can not use existing template.
This new job template adds the possibility to build and publish `redhat.openshift` collection to automation

Add job template to publish redhat.openshift on automation hub

---

playbooks/config/check.yaml

This change fixes the managesf-resources location on RHEL9.

Update the config-check managesf resource path

---

playbooks/config/check.yaml
zuul.d/pipelines.yaml

Fix the following error 
```
The trigger configuration as supplied has an error: expected a list for dictionary value @ data['state']
```
Please refer to the configuration here is the source code
https://opendev.org/zuul/zuul/src/commit/b39a5cae99eb108da426d8d02cc8a17f895c468f/zuul/driver/github/githubtrigger.py#L139-L215

Fix pipeline configuration error

---

zuul.d/secrets.yaml

This changes the hostname of the update server to match the hostname in the known_hosts entry.
I think this may fix the current issue with the config update failing (https://ansible.softwarefactory-project.io/zuul/build/d3f69faa81e64b4aa429564eda1b693c/log/job-output.txt#270).
The host key was changed about six months ago in https://github.com/ansible/zuul-config/commit/cb56036fc2b1f36189e7fd10d6b37de6344d3e4c. The `fqdn` variable is used in https://github.com/ansible/zuul-config/blob/0d4cd448372907f08b3c692f55f01bb2e75d6bd2/playbooks/config/update_tenant.yaml#L33-L36 and I think this needs to match the hostname in the known_hosts entry. I don't know why this wouldn't have been a problem until now.

Update hostname for site_tenant_update

---

resources/ansible.yaml

The config update is correctly working now after #582 but the tenant update never happened (https://ansible.softwarefactory-project.io/zuul/build/957938387d794aa29e9d3845ba63b7fe/log/job-output.txt#269). This is preventing #580 from being merged. I think the problem is because of https://github.com/ansible/zuul-config/blob/a32c955bd6beb6a88a6f2bffcc405583c1da634f/playbooks/config/update_tenant.yaml#L40
The update block has not been successfully run since the recent changes to `resources/ansible.yaml`. I think just changing this file should make the tenant update happen. This undoes my previous attempt to get things working.
This reverts commit be5bddd92089e04469d3dbc519aa61fe77880eba.

Revert "Try and force config update"

---

resources/ansible.yaml

After seeing the other failures that are happening in community.vmware and https://github.com/ansible/ansible-zuul-jobs/pull/1892, I think its best to add these back in

add vmware_rest back into config for other projects

---

roles/upload-ansible-collection-fork/tasks/main.yaml

This PR reverts the temporary work around added in https://github.com/ansible/zuul-config/pull/584

Remove temporary work around to publish a collection
