- zuul.d/jobs.yaml
- zuul.d/pipelines.yaml
- zuul.d/secrets.yaml
The connection is named github.com
> Add logserver secret and fix pipeline reporter name

- playbooks/base-minimal-test/pre.yaml
This outputs some helpful information for users when trying to debug
jobs.
> base-minimal-test: Include emit-job-header / log-inventory roles

- resources/ansible.yaml
Depends-On: https://github.com/ansible/zuul-config/pull/18
> Add ansible/awx to zuul configuration

- zuul.d/projects.yaml
Depends-On: https://github.com/ansible/zuul-jobs/pull/9
> Adding default tox jobs for runner and awx

- zuul.d/projects.yaml
depends-on: https://github.com/ansible/zuul-jobs/pull/14
> Switch the awx project template

- playbooks/base-minimal/pre.yaml
This reverts commit f7a048d28ca832c238c0a3ce5bb9fe9692d9ad3f.
> Revert "base: become before cleaning"

- playbooks/staticnodes/configure.yaml
* https://success.docker.com/article/ipv4-forwarding
> fix network error

- resources/ansible.yaml
We no longer want to gate this repo with zuul.
> Remove ansible/zuul-test-repo from zuul

- roles/run_awx_tests/tasks/main.yml
> Fix errors on jobs that do not declare artifacts

- playbooks/awx-push-new-schema.yaml
This will cause issues until https://github.com/ansible/zuul-jobs/pull/30 is merged
> Revert change to gate playbook

- playbooks/awx-push-new-schema.yaml
This reverts commit 7791c813857fe8ab3126ec571e3f65a0d7238136.
> Revert "Revert change to gate playbook"

- zuul.d/projects.yaml
relates to https://github.com/ansible/awx/pull/4932 and https://github.com/ansible/zuul-jobs/pull/37
> Combine ui test jobs

- playbooks/config/check.yaml
- resources/_internal.yaml
This change also tests the new ansible.sf-project.io instance.
> Update config-check job

- roles/run_awx_tests/tasks/main.yml
Let's see if the nodes can handle this.
> WIP: Run tests on zuul node

- roles/run_awx_tests/defaults/main.yml
- roles/run_awx_tests/tasks/main.yml
See https://github.com/ansible/awx/pull/7017
> Create dockerfile for build if needed.

- playbooks/base-minimal/post.yaml
- playbooks/base-openshift/post.yaml
https://opendev.org/zuul/zuul-jobs/commit/c24c09e82c9bc5028b2f0fd371060b7b8d448c39
> Update ara_report_path due to recent changes in zuul-jobs

- resources/ansible.yaml
- zuul.d/projects.yaml
Depends-On: https://github.com/ansible/zuul-config/pull/101
> add ansible-collections/cloud.common

- playbooks/base/README
- playbooks/base/post.yaml
- playbooks/base/pre.yaml
The previous PR was missing the playbook. *facepalm*
> Add missing base playbooks

- resources/ansible.yaml
> include ansible/ansible-zuul-jobs as config source

- resources/ansible.yaml
> remove zuul-jobs from the configuration

- zuul.d/projects.yaml
See: https://zuul-ci.org/docs/zuul/reference/pragma_def.html#pragma
> use implied-branches to target main

- resources/ansible.yaml
See: https://softwarefactory-project.io/r/c/config/+/23397
> exclude-unprotected-branches is True by default now

- resources/ansible.yaml
Include all the existing projects with `include: []`.
> include all the existing projects

- playbooks/base/pre.yaml
Fix a typo introduced byhttps://github.com/ansible/zuul-config/pull/177
> address a syntax error

- playbooks/buildset-registry/post.yaml
- playbooks/buildset-registry/pre.yaml
- playbooks/buildset-registry/run.yaml
- playbooks/container-image/upload.yaml
- zuul.d/jobs-ee.yaml
Import the following jobs:
- ansible-buildset-registry
- ansible-buildset-registry-consumer
- ansible-upload-container-image
From project-config 33645d7f75efeae87c48deec52305cea63c4c904.
> import registry related jobs

- playbooks/base/post.yaml
- zuul.d/jobs.yaml
- zuul.d/secrets.yaml
We need to reconfigure the Content-Security-Policty of the webserver first.
See: https://softwarefactory-project.io/cgit/software-factory/sf-config/tree/ansible/roles/sf-gateway/templates/headers.conf.j2
This reverts commit 998d580f56e901238a808ccacd65b6f647d823b0.
> Revert "also upload logs on RAX Object Store"

- playbooks/base/post.yaml
- zuul.d/jobs.yaml
- zuul.d/secrets.yaml
Reenable the upload to RAX and turn off the `zuul_log_compress` off.
This reverts commit eb81c56c7b9c96b5e8adbb31ac8eb6861bbc3b96.
> Revert "Revert "also upload logs on RAX Object Store""

- resources/ansible.yaml
This to reduce the pressure on Zuul and the Github API rate limit.
> remove vmware/ projects

- resources/ansible.yaml
Disable the project .zuul.d/ directories to avoid any problem
with jobs depending on zuul.ansible.com.
> resources: ensure we don't load the projects .zuul.d/

- playbooks/build-ansible-collection-pod/run.yaml
ansible_user_dir is set as /root, we expect /.
> build-ansible-collection-pod: fix ansible_user_dir

- playbooks/build-ansible-collection-pod/run.yaml
This reverts commit d6836316ade620f09e1c41fd559b6932b13cf410.
> Revert "build-ansible-collection-pod: add trace to understand the net problem"

- playbooks/build-ansible-collection-pod/post.yaml
- playbooks/build-ansible-collection-pod/run.yaml
- playbooks/build-ansible-collection/pre.yaml
- playbooks/build-ansible-collection/run.yaml
- zuul.d/jobs.yaml
Reverting until the overlayfs problem is resolved.
This reverts commit f5bb0c920d93952dc1c2b8fd9aeae24fd0678056.
> Revert "build-ansible-collection: use container by default"

- playbooks/base/pre.yaml
To troubleshoot the network issue with EOS.
> dump hostvars

- playbooks/base/pre.yaml
This reverts commit a2390466d6786cd56e8577ff0409ca28cdeb2f1f.
> Revert "dump hostvars"

- zuul.d/projects.yaml
Depends-On: https://github.com/ansible-collections/openvswitch-openvswitch
> ovs: use the regular ansible-collections-openvswitch-openvswitch

- zuul.d/projects.yaml
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1332
> ansible-utils: use ansible-collections-ansible-utils

- zuul.d/jobs.yaml
- zuul.d/projects.yaml
- zuul.d/secrets.yaml
- ansible/ansible-builder
- ansible/ansible-core-image
- ansible/ansible-navigator
- ansible/ansible-runner
- ansible/network
> move more jobs to SF

- playbooks/ansible-collection/twitter.yaml
Adjust the path pointing on `releases` directory.
> ansible-collection/twitter: adjust path of releases

- zuul.d/secrets.yaml
> refresh the twitter_ansible_content password

- resources/ansible.yaml
Zuul will be used to build, test and publish images.
> Add ansible-community/images

- resources/ansible.yaml
Signed-off-by: NilashishC <nilashishchakraborty8@gmail.com>
> Add ansible.plugin_builder

- resources/ansible.yaml
resources/ansible.yaml: add community.lbry to publish it on Galaxy
> resources/ansible.yaml: add community.lbry to publish it on Galaxy

- zuul.d/projects.yaml
See: https://github.com/ansible/ansible-zuul-jobs/pull/1389
> eos: enable the integration jobs

- zuul.d/projects.yaml
> qradar: add the test coverage

- resources/ansible.yaml
See: https://github.com/ansible/ansible-zuul-jobs/pull/1403
> resources: define amazon.cloud

- zuul.d/projects.yaml
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1403
> enable amazon.cloud

- zuul.d/projects.yaml
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1406
> Add the amazon cloud code generator project

- scripts/upload-network-image.sh
> script used to upload network images

- playbooks/ansible-collection/twitter.yaml
Port of https://github.com/ansible/project-config/pull/1050 to this repo
> Change cloud.redhat.com to console.redhat.com

- zuul.d/jobs.yaml
See: https://github.com/ansible/ansible-zuul-jobs/pull/1421
> use regular VM until the k1s problem is fixed

- zuul.d/jobs.yaml
This reverts commit bf82b720f9ec7ebcddb6426de0e7d2f42ba9c5d7.
> Revert "use regular VM until the k1s problem is fixed"

- playbooks/ansible-collection/pre.yaml
> release: jobs depend on ansible-core

- zuul.d/projects.yaml
As far as I can tell, all the underlying tests have moved, so this should work?
> Move netcommon tests to sf

- zuul.d/projects.yaml
Signed-off-by: Rohit Thakur <rohitthakur2590@outlook.com>
> define ansible.yang

- playbooks/downstream-ee/pre.yaml
> typo: podmane -> podman

- playbooks/config/check.yaml
- playbooks/config/config-update.yaml
- playbooks/config/update_local.yaml
- playbooks/config/update_tenant.yaml
- zuul.d/jobs.yaml
This change pulls the latest change to run config-check on sf-3.7 tenants.
> Update the config playbook

- playbooks/base/post.yaml
Use the standard config/playbooks/base/post.yaml from SF
commit: bded459840be4876be77ca59d7f75c69b04cbf02
This until we resolve the ongoing problem with RAX.
> RAX issue: partially rollback on standard config/playbooks/base/post.yaml from SF

- playbooks/base/post.yaml
Use version from ab2c7f6c02b5b5c6d71ba3d99810940959ecc393.
> restore playbooks/base/post.yaml from before the RAX problem

- zuul.d/secrets.yaml
note: this secret was generated using my personal account. We will need
to reupload later one based on the ansible-ci user
> import rhsm.pullsecret

- zuul.d/projects.yaml
- This remove the ansible.utils job
> Remove utils job

- zuul.d/jobs.yaml
See: https://github.com/ansible/ansible-zuul-jobs/pull/1545
> remove build-ansible-collection

- zuul.d/projects.yaml
Signed-off-by: Rohit Thakur <rohitthakur2590@outlook.com>
> Remove Junos units deps

- zuul.d/projects.yaml
Signed-off-by: NilashishC <nilashishchakraborty8@gmail.com>
> Remove NX-OS job

- zuul.d/projects.yaml
> Remove eos and vyos unit test jobs

- playbooks/base/pre.yaml
This is already handled at the cloud provider level.
> don't register the RHEL nodes on AWS

- zuul.d/projects.yaml
> remove jobs for ios and iosxr

- resources/ansible.yaml
Add ansible/aws-ci-admin to zuul tenants
> Add ansible/aws-ci-admin to zuul tenants

- zuul.d/projects.yaml
Add ansible/aws-ci-admin project
> Add ansible/aws-ci-admin project

- zuul.d/projects.yaml
Signed-off-by: NilashishC <nilashishchakraborty8@gmail.com>
> Remove plugin builder jobs

- README.rst
> README.rst: zuul/tenants.yaml -> resources/ansible.yaml

- zuul.d/projects.yaml
ibm.csm: add to auto-publishing by Zuul
> ibm.csm: add to auto-publishing by Zuul

- README.rst
README: update PR2 paragraph to reflect some new nuances
> README: update PR2 paragraph to reflect some new nuances

- README.rst
> README: fix ref markup

- resources/ansible.yaml
Add resources for cip and osbuild repos
> cip resources

- zuul.d/projects.yaml
Add repos for CIP and osbuild to be able to do galaxy releases
Depends-On: #454
> Add repos for CIP and osbuild

- resources/ansible.yaml
- zuul.d/projects.yaml
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1663
Add cloud.aws_troubleshooting
> Add cloud.aws_troubleshooting

- resources/ansible.yaml
Add ansible-collections/cloud.aws_ops to resources
> Add ansible-collections/cloud.aws_ops to resources

- zuul.d/projects.yaml
Add ansible-collections/cloud.aws_ops to zuul.d/projects
> Add ansible-collections/cloud.aws_ops to zuul.d/projects

- resources/ansible.yaml
See: https://issues.redhat.com/browse/RHOSZUUL-1039
> removed ansible.posix until the rate limit is fixed

- resources/ansible.yaml
See: https://github.com/ansible/ansible-zuul-jobs/pull/1691#issuecomment-1309191880
> reverse the recent projects deactivation

- zuul.d/projects.yaml
Signed-off-by: rohitthakur2590 <rohitthakur2590@outlook.com>
> Add Galaxy and AH jobs

- resources/ansible.yaml
Adding a new collection https://github.com/ansible-collections/gouttelette
> Add resource - gouttelette

- zuul.d/projects.yaml
Enable CI on ansible-collections/gouttelette
> Enable CI on ansible-collections/gouttelette

- zuul.d/projects.yaml
This reverts commit 05ba47859353395542d75ec240e8c63a4a0fcdb2.
> Revert "cloud.terraform: associate ansible-collections-cloud-terraform-units"

- zuul.d/projects.yaml
> Enable unit tests on ansible-collections/gouttelette

- resources/ansible.yaml
relates to https://github.com/ansible-collections/overview/issues/222
after merging this one, merge https://github.com/ansible/zuul-config/pull/498
> resources/ansible.yaml: add community.elastic

- resources/ansible.yaml
Relates to https://github.com/ansible-collections/overview/issues/221
> resources/ansible.yaml: add community.pacemaker

- zuul.d/projects.yaml
Depends-on: https://github.com/ansible/zuul-config/pull/500
> Drop unused ansible-collections-ansible-netcommon-units template

- zuul.d/projects.yaml
Merge after https://github.com/ansible/zuul-config/pull/497
Relates to https://github.com/ansible-collections/overview/issues/222
> zuul.d/projects.yaml: add community.elastic

- resources/ansible.yaml
resources/ansible.yaml: add community.sonic
> resources/ansible.yaml: add community.sonic

- resources/ansible.yaml
resources/ansible.yml: add ibm.storage_virtualize
> resources/ansible.yml: add ibm.storage_virtualize

- zuul.d/secrets.yaml
Stage PR to rotate Galaxy and AH publishing keys.  Currently scheduled for Tuesday Oct 3.
> Rotate Galaxy and AH publishing keys

- zuul.d/secrets.yaml
After the galaxy-ng API cutover all tokens need to be regenerated
> Rotate Galaxy token, for galaxy-ng cutover

- zuul.d/secrets.yaml
We are having failures with the token validation job; re-encrypt and upload token after confirming the de-crypted token works with this job
> Re-encrypt galaxy token for ansibuddy

- resources/ansible.yaml
- zuul.d/projects.yaml
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>
- Bugfix Pull Request
> Remove servicenow.itsm tests

- resources/ansible.yaml
Append new Ansible Collections for SAP to zuul-config
> Add new SAP collection

- resources/ansible.yaml
relates to https://github.com/ansible-collections/overview/issues/232
> resources/ansible.yaml: add community.proxmox

- resources/ansible.yaml
Collection needs to release to AH when tagged, only going to galaxy now
> Add AH publishing for servicenow.itsm

- zuul.d/projects.yaml
> Enable snow jobs

- resources/ansible.yaml
- zuul.d/projects.yaml
Remove ansible.security from zuul config
> Remove ansible security

- resources/ansible.yaml
Ref: https://github.com/ansible-community/images/pull/88
> Remove ansible-community/images from Zuul config

- zuul.d/projects.yaml
> Add new collections to projects

- resources/ansible.yaml
Trying to force a config update with an inconsequential change to see if it will pass this time.
> Try and force config update

- zuul.d/projects.yaml
related https://github.com/ansible/zuul-config/pull/587/files
> add vmware_rest back into projects.yml

- resources/ansible.yaml
- zuul.d/projects.yaml
I removed the vmware_rest jobs recently and alina suggested removing vmware_rest_code_generator too since its not used
> remove vmware_rest_code_generator project since its also not used

- resources/ansible.yaml
- zuul.d/projects.yaml
https://github.com/ansible-collections/community.proxmox
CC @gundalow @Thulium-Drake @WaitingAtTheCrossroads
> Add community.proxmox

- resources/ansible.yaml
resources/ansible.yaml: Add community.beszel
> resources/ansible.yaml: Add community.beszel
